import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBar from '../../components/SideBar'
import TopNavbar from '../../components/TopNavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AnimeTrix',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className }>
        <div className='flex bg-green-700 h-screen'>
        <SideBar/>
        <div className='flex-1 flex flex-col min-w-0'>
        <TopNavbar/>
        {children}
        </div>
        </div>
      </body>
    </html>
  )
}
